# Generated by Django 5.0.2 on 2024-03-07 07:07

import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BowlingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=75)),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'Bowling Center',
                'ordering': ['state', 'center_name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email_address', models.EmailField(max_length=128)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('profile_picture', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Tournament Director',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('bowling_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.bowlingcenter')),
                ('tournament_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentdirector')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
