# Generated by Django 5.0.2 on 2024-03-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bowlingcenter',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='bowlingcenter',
            name='address_2',
        ),
    ]
