# Generated by Django 5.0.2 on 2024-03-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_rename_address_1_bowlingcenter_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournamentdirector',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
