# Generated by Django 5.0.2 on 2024-03-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_options_remove_tournament_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowlingcenter',
            name='website',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='tournament',
            name='flyer',
            field=models.FileField(blank=True, upload_to='tournament_flyers'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='website',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='bowlingcenter',
            name='center_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tournamentdirector',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
