# Generated by Django 5.0.2 on 2024-03-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
