# Generated by Django 5.0.2 on 2024-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('logged_in', models.BooleanField(default=False)),
            ],
        ),
    ]
